<?php

add_action( 'init', function() {
	register_taxonomy( 'portfolio-cat', array(
	0 => 'portfolio',
), array(
	'labels' => array(
		'name' => 'Portfolios Cat',
		'singular_name' => 'Portfolio Cat',
		'menu_name' => 'Portfolios Cat',
		'all_items' => 'All Portfolios Cat',
		'edit_item' => 'Edit Portfolio Cat',
		'view_item' => 'View Portfolio Cat',
		'update_item' => 'Update Portfolio Cat',
		'add_new_item' => 'Add New Portfolio Cat',
		'new_item_name' => 'New Portfolio Cat Name',
		'search_items' => 'Search Portfolios Cat',
		'not_found' => 'No portfolios cat found',
		'no_terms' => 'No portfolios cat',
		'items_list_navigation' => 'Portfolios Cat list navigation',
		'items_list' => 'Portfolios Cat list',
		'back_to_items' => '← Go to portfolios cat',
		'item_link' => 'Portfolio Cat Link',
		'item_link_description' => 'A link to a portfolio cat',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'portfolio', array(
	'labels' => array(
		'name' => 'Portfolios',
		'singular_name' => 'Portfolio',
		'menu_name' => 'portfolios',
		'all_items' => 'All portfolios',
		'edit_item' => 'Edit portfolio',
		'view_item' => 'View portfolio',
		'view_items' => 'View portfolios',
		'add_new_item' => 'Add New portfolio',
		'add_new' => 'Add New portfolio',
		'new_item' => 'New portfolio',
		'parent_item_colon' => 'Parent portfolio:',
		'search_items' => 'Search portfolios',
		'not_found' => 'No portfolios found',
		'not_found_in_trash' => 'No portfolios found in Trash',
		'archives' => 'portfolio Archives',
		'attributes' => 'portfolio Attributes',
		'insert_into_item' => 'Insert into portfolio',
		'uploaded_to_this_item' => 'Uploaded to this portfolio',
		'filter_items_list' => 'Filter portfolios list',
		'filter_by_date' => 'Filter portfolios by date',
		'items_list_navigation' => 'portfolios list navigation',
		'items_list' => 'portfolios list',
		'item_published' => 'portfolio published.',
		'item_published_privately' => 'portfolio published privately.',
		'item_reverted_to_draft' => 'portfolio reverted to draft.',
		'item_scheduled' => 'portfolio scheduled.',
		'item_updated' => 'portfolio updated.',
		'item_link' => 'portfolio Link',
		'item_link_description' => 'A link to a portfolio.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-portfolio',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'service', array(
	'labels' => array(
		'name' => 'Services',
		'singular_name' => 'Service',
		'menu_name' => 'Services',
		'all_items' => 'All Services',
		'edit_item' => 'Edit Service',
		'view_item' => 'View Service',
		'view_items' => 'View Services',
		'add_new_item' => 'Add New Service',
		'add_new' => 'Add New Service',
		'new_item' => 'New Service',
		'parent_item_colon' => 'Parent Service:',
		'search_items' => 'Search Services',
		'not_found' => 'No services found',
		'not_found_in_trash' => 'No services found in Trash',
		'archives' => 'Service Archives',
		'attributes' => 'Service Attributes',
		'insert_into_item' => 'Insert into service',
		'uploaded_to_this_item' => 'Uploaded to this service',
		'filter_items_list' => 'Filter services list',
		'filter_by_date' => 'Filter services by date',
		'items_list_navigation' => 'Services list navigation',
		'items_list' => 'Services list',
		'item_published' => 'Service published.',
		'item_published_privately' => 'Service published privately.',
		'item_reverted_to_draft' => 'Service reverted to draft.',
		'item_scheduled' => 'Service scheduled.',
		'item_updated' => 'Service updated.',
		'item_link' => 'Service Link',
		'item_link_description' => 'A link to a service.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-editor-insertmore',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'testimonial', array(
	'labels' => array(
		'name' => 'Testimonials',
		'singular_name' => 'Testimonial',
		'menu_name' => 'Testimonials',
		'all_items' => 'All Testimonials',
		'edit_item' => 'Edit Testimonial',
		'view_item' => 'View Testimonial',
		'view_items' => 'View Testimonials',
		'add_new_item' => 'Add New Testimonial',
		'add_new' => 'Add New Testimonial',
		'new_item' => 'New Testimonial',
		'parent_item_colon' => 'Parent Testimonial:',
		'search_items' => 'Search Testimonials',
		'not_found' => 'No testimonials found',
		'not_found_in_trash' => 'No testimonials found in Trash',
		'archives' => 'Testimonial Archives',
		'attributes' => 'Testimonial Attributes',
		'insert_into_item' => 'Insert into testimonial',
		'uploaded_to_this_item' => 'Uploaded to this testimonial',
		'filter_items_list' => 'Filter testimonials list',
		'filter_by_date' => 'Filter testimonials by date',
		'items_list_navigation' => 'Testimonials list navigation',
		'items_list' => 'Testimonials list',
		'item_published' => 'Testimonial published.',
		'item_published_privately' => 'Testimonial published privately.',
		'item_reverted_to_draft' => 'Testimonial reverted to draft.',
		'item_scheduled' => 'Testimonial scheduled.',
		'item_updated' => 'Testimonial updated.',
		'item_link' => 'Testimonial Link',
		'item_link_description' => 'A link to a testimonial.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-images-alt',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'editor',
	),
	'delete_with_user' => false,
) );
} );

